import { type PropsWithChildren } from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
type RoutesLayoutProps = PropsWithChildren

function RoutesLayout({ children }: RoutesLayoutProps) {
  return <main>{children}</main>
}

export default RoutesLayout
